import * as React from "react";
import Head from "next/head";

const Success = () => {
  return (
    <>
      <Head>
        <title>The Toggle Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/osmo.png" />
      </Head>
      <body>
        <section>
          <p>
            We appreciate your business! If you have any questions, please email
            <a href="mailto:orders@example.com">orders@example.com</a>.
          </p>
        </section>
      </body>
    </>
  );
};
export default Success;
