import * as React from "react";
import { useState, useEffect } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { blueDark } from "@radix-ui/colors";
import { Table } from "@nextui-org/react";
import DatabaseState from "@/components/database-status";
import product from "@/config/products";
import { useFlags } from "launchdarkly-react-client-sdk";
import NavigationMenuDemo from "@/components/menu";
import { styled } from "@stitches/react";

type Inventory = {
  id: number;
  toggle_name: string;
  price: string;
  description: string;
};

type Orders = {
  name: string;
  email: string;
};

type Product = {
  name: string;
  table_price: string;
  inventory: number;
};

const InventoryPage = () => {
  const { devdebug, dbTesting } = useFlags();
  const [inventory, setInventory] = useState<Inventory[]>([]);
  const [orders, setOrders] = useState<Orders[]>([]);

  const getInventory = async () => {
    try {
      console.log("calling external inventory");
      const response = await fetch("/api/inventory");
      const jsonData = await response.json();
      setInventory(jsonData);
    } catch (error) {
      console.log("there was an error");
    }
  };

  const getOrders = async () => {
    try {
      console.log("caught db testing change");
      const response = await fetch("/api/form");
      const jsonData = await response.json();
      setOrders(jsonData);
    } catch (error) {
      console.log("there was an error");
    }
  };

  useEffect(() => {
    getInventory();
    getOrders();
  }, [dbTesting]);

  return (
    <>
      <Head>
        <title>The Toggle Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/osmo.png" />
      </Head>
      <header className={styles.header}>
        <NavigationMenuDemo />
      </header>
      <main className={styles.main}>
        {devdebug && <DatabaseState />}
        <InvText style={{ padding: "10px" }}>Current Inventory</InvText>
        {dbTesting == "postgres" ? (
          <Table
            css={{
              height: "auto",
              width: "1250px",
              backgroundColor: "white",
              alignContent: "right",
            }}
            selectionMode="single"
          >
            <Table.Header>
              <Table.Column>TOGGLE NAME</Table.Column>
              <Table.Column>PRICE</Table.Column>
              <Table.Column>DESCRIPTION</Table.Column>
              <Table.Column>CURRENT INVENTORY</Table.Column>
              <Table.Column>OUTSTANDING ORDERS</Table.Column>
            </Table.Header>
            <Table.Body>
              {inventory.map((inventory: Inventory) => (
                <Table.Row>
                  <Table.Cell>{inventory.toggle_name}</Table.Cell>
                  <Table.Cell>{inventory.price}</Table.Cell>
                  <Table.Cell>{inventory.description}</Table.Cell>
                  <Table.Cell>{Math.floor(Math.random() * 100)}</Table.Cell>
                  <Table.Cell>{Math.floor(Math.random() * 10)}</Table.Cell>
                </Table.Row>
              ))}
            </Table.Body>
          </Table>
        ) : (
          <Table
            css={{
              height: "auto",
              width: "500px",
              backgroundColor: "white",
              alignContent: "center",
            }}
            selectionMode="single"
          >
            <Table.Header>
              <Table.Column>TOGGLE NAME</Table.Column>
              <Table.Column>PRICE</Table.Column>
              <Table.Column>CURRENT INVENTORY</Table.Column>
            </Table.Header>
            <Table.Body>
              {product.map((product: Product) => (
                <Table.Row>
                  <Table.Cell>{product.name}</Table.Cell>
                  <Table.Cell>{product.table_price}</Table.Cell>
                  <Table.Cell>{product.inventory}</Table.Cell>
                </Table.Row>
              ))}
            </Table.Body>
          </Table>
        )}
        <br></br>
        <InvText style={{ padding: "10px" }}>Current Orders</InvText>
        <Table
          css={{
            height: "auto",
            width: "500px",
            backgroundColor: "white",
            alignContent: "center",
          }}
          selectionMode="single"
        >
          <Table.Header>
            <Table.Column>NAME</Table.Column>
            <Table.Column>EMAIL</Table.Column>
          </Table.Header>
          <Table.Body>
            {orders.map((orders: Orders) => (
              <Table.Row key="1">
                <Table.Cell>{orders.name}</Table.Cell>
                <Table.Cell>{orders.email}</Table.Cell>
              </Table.Row>
            ))}
          </Table.Body>
        </Table>
      </main>
    </>
  );
};

const InvText = styled("h1", {
  color: "white",
});

export default InventoryPage;
